# Generated by Django 3.0 on 2023-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='article',
        ),
        migrations.AddField(
            model_name='blog',
            name='article',
            field=models.ManyToManyField(blank=True, to='base.Article'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_article',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_article',
            field=models.ManyToManyField(blank=True, to='base.Image_article'),
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story',
        ),
        migrations.AddField(
            model_name='stories',
            name='story',
            field=models.ManyToManyField(blank=True, to='base.Story'),
        ),
        migrations.RemoveField(
            model_name='vocabularies',
            name='vocabulary',
        ),
        migrations.AddField(
            model_name='vocabularies',
            name='vocabulary',
            field=models.ManyToManyField(blank=True, to='base.Vocabulary'),
        ),
    ]
