# Generated by Django 3.0 on 2023-08-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230822_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='story',
            name='title_arabic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
