# Generated by Django 3.0 on 2023-08-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230822_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
