# Generated by Django 3.0 on 2023-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230824_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='sentence_arabic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sentence_english',
            field=models.TextField(blank=True, null=True),
        ),
    ]
