# Generated by Django 3.0 on 2023-08-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230824_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabularies',
            name='vocabulary',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='vocabulary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Vocabularies'),
            preserve_default=False,
        ),
    ]
