# Generated by Django 3.0 on 2023-09-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230824_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_english', models.CharField(max_length=200, null=True)),
                ('sentence_arabic', models.CharField(max_length=200, null=True)),
                ('song', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
