# Generated by Django 3.0 on 2023-09-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_adj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_english', models.CharField(max_length=200, null=True)),
                ('sentence_arabic', models.CharField(max_length=200, null=True)),
                ('song', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Phrasal_Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_english', models.CharField(max_length=200, null=True)),
                ('sentence_arabic', models.CharField(max_length=200, null=True)),
                ('song', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Slang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_english', models.CharField(max_length=200, null=True)),
                ('sentence_arabic', models.CharField(max_length=200, null=True)),
                ('song', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Useful_sentene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_english', models.CharField(max_length=200, null=True)),
                ('sentence_arabic', models.CharField(max_length=200, null=True)),
                ('song', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
