# Generated by Django 3.0 on 2023-09-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_common_word_phrasal_verb_slang_useful_sentene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='article',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_article',
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title_arabic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image_article',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.Blog'),
            preserve_default=False,
        ),
    ]
