# Generated by Django 3.0 on 2023-09-10 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20230910_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_article',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
