# Generated by Django 3.0 on 2023-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20230910_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversations',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabularies',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
